export const colors = [
  { name: "مشکی", hex: "#000000" },
  { name: "سفید", hex: "#FFFFFF" },
  { name: "خاکستری", hex: "#808080" },
  { name: "نقره‌ای", hex: "#C0C0C0" },
  { name: "قرمز", hex: "#FF0000" },
  { name: "قرمز تیره", hex: "#8B0000" },
  { name: "صورتی", hex: "#FFC0CB" },
  { name: "بنفش", hex: "#800080" },
  { name: "بنفش روشن", hex: "#D8BFD8" },
  { name: "آبی", hex: "#0000FF" },
  { name: "آبی تیره", hex: "#00008B" },
  { name: "سبز", hex: "#008000" },
  { name: "سبز تیره", hex: "#006400" },
  { name: "زرد", hex: "#FFFF00" },
  { name: "طلایی", hex: "#FFD700" },
  { name: "نارنجی", hex: "#FFA500" },
  { name: "قهوه‌ای", hex: "#A52A2A" },
  { name: "کاراملی", hex: "#D2691E" },
  { name: "بژ", hex: "#F5F5DC" },
  { name: "کرمی", hex: "#FFFDD0" },
];
